name: Build Ubuntu Images

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      publish:
        type: boolean
        default: false
        description: Publish built image

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - xenial
          - bionic
          - focal
          - jammy
          - mantic
          # - noble
        architecture:
          - amd64
          # - arm64
        variant:
          - default
          - desktop
          - cloud
    env:
      type: "container"
      distro: "${{ github.job }}"
      target: "${HOME}/build"

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/image-setup

      - name: Determine image types
        run: |
          ARCH="${{ matrix.architecture }}"
          if [ "${ARCH}" = "amd64" ] || [ "${ARCH}" = "arm64" ]; then
              echo "type=container,vm" >> $GITHUB_ENV
          fi

          if [ "${{ matrix.variant }}" = "desktop" ]; then
              echo "type=vm" >> $GITHUB_ENV
          fi

      - name: Build image
        run: |
          TIMEOUT=3600
          YAML="${{ github.workspace }}/lxd-ci/images/${{ env.distro }}.yaml"
          ARCH="${{ matrix.architecture }}"
          TYPE="${{ env.type }}"

          ARCHIVE="http://archive.ubuntu.com/ubuntu"
          if [ "${ARCH}" != "amd64" ] && [ "${ARCH}" != "i386" ]; then
              ARCHIVE="http://ports.ubuntu.com/ubuntu-ports"
          fi

          ./bin/build-distro "${YAML}" "${ARCH}" "${TYPE}" "${TIMEOUT}" "${{ env.target }}" \
              -o image.architecture=${{ matrix.architecture }} \
              -o image.release=${{ matrix.release }} \
              -o image.variant=${{ matrix.variant }} \
              -o source.url="${ARCHIVE}"

      - name: Print build artifacts
        run: ls -lah "${{ env.target }}"

      - name: Test container image
        uses: ./.github/actions/image-test
        if: contains(env.type, 'container')
        with:
          type: container
          target: ${{ env.target }}
          distro: ${{ env.distro }}
          release: ${{ matrix.release }}
          variant: ${{ matrix.variant }}

      - name: Test VM image
        uses: ./.github/actions/image-test
        if: contains(env.type, 'vm')
        with:
          type: vm
          target: ${{ env.target }}
          distro: ${{ env.distro }}
          release: ${{ matrix.release }}
          variant: ${{ matrix.variant }}

      - name: Upload image
        uses: ./.github/actions/image-upload
        if: inputs.publish == true
        with:
          name: "${{ env.distro }}-${{ matrix.release }}-${{ matrix.architecture }}-${{ matrix.variant }}"
          target: ${{ env.target }}
          # types: ${{ env.type }}
